### ISSUE TITLE
[Umbrella] GCS fault tolerance on KubeRay 

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#1033]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

#### Ray
- [ ] https://github.com/ray-project/ray/issues/34507
- [x] https://github.com/ray-project/ray/issues/39122
- [x] https://github.com/ray-project/kuberay/issues/1424
- [x] https://github.com/ray-project/kuberay/issues/1286#issuecomment-1684023989 
  - [ ] #959

#### KubeRay
- [x] #1036 
- [x] #1286 
- [x] #1296 
- [x] #1297 [WIP]
- [x] #1341
- [x] #1144 
- [x] #1353
- [x] #1354
- [x] #1355
- [x] #1557 
- [x] https://github.com/ray-project/ray/issues/40562

* Under discussions
  - [ ] #1356

#### KubeRay tests / docs
- [x] https://github.com/ray-project/kuberay/issues/1421
- [ ] https://github.com/ray-project/kuberay/issues/1422
- [ ] https://github.com/ray-project/kuberay/issues/1393

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!
