### ISSUE TITLE
[Umbrella] KubeRay health-check mechanism

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#1657]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description
- [x] #1656

- [x] Add related probes to check the status of the dashboard agent.
     - [x] #1674 
- [ ] Revisit the definitions of `LastTimeUpdate` and `HealthLastTimeUpdate`. See [here](https://github.com/ray-project/kuberay/pull/1581/files#r1376729892) for more details.
     - [x] #1659
     - [x] #1666 

- [x] Remove health checks for Ray dashboard agent and Ray Serve applications.
     - [x] #1660
     - [x] #1664
     - [x] #1665 

- [ ] CRD
     - [ ] `DeploymentUnhealthySecondThreshold`
        - [x] Mark as deprecated
           - [x] #1688
        - [ ] Deprecate it after 1 or 2 minor releases.
     - [ ] `ServiceUnhealthySecondThreshold`
        - [x] Mark as deprecated
           - [x] #1688     
        - [ ] Deprecate it after 1 or 2 minor releases.
     - [x] Update YAMLs
     - [ ] Update docs

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!
