### ISSUE TITLE
[Umbrella] RayService HA tests

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#2177]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

We plan to add tests for RayService HA. The HA tests includes two parts. 

* [P0] "Normal cases": In normal cases, no request should be dropped.
  - [x] Static RayCluster #2176 
  - [x] #2480
  - [x] #2517

* [P1] "Chaos cases": In chaos cases, some requests may be dropped.
   - [x] https://github.com/ray-project/kuberay/issues/2577
   - [x] https://github.com/ray-project/kuberay/issues/2593

* #2518 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by CheyuWu** [comment]
@kevin85421 I'd like to help with this
