### ISSUE TITLE
[Umbrella] Remove the RayCluster `.Status.State` field

### ISSUE THREAD

**Issue by rueian** [ray-project/kuberay#2299]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

In the progress of https://github.com/ray-project/enhancements/pull/54, we have added the new `.Status.Conditions` field to replace the single `.Status.State`. The next step is to remove the `.Status.State field`. It is a long-term process, starting from deprecating the field. This issue is meant to track the whole progress.

- [ ] https://github.com/ray-project/kuberay/pull/2288
- [ ] Document the deprecation in v1.2.0.
- [ ] Remove its `+kubebuilder:printcolumn` annotation in v1.3.0 if the new `.Status.Conditions` field works well.
- [ ] Remove the `.Status.State` in v2.0.0 if the new `.Status.Conditions` field works well.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by JasonChen86899** [comment]
I have reviewed the document and briefly summarized the status of this field `.Status.Conditions`
1. RayClusterSuspending
2. RayClusterSuspended
3. RayClusterAvailable / RayClusterReady
4. RayClusterK8sFailure
5. RayClusterReplicaFailure
