### ISSUE TITLE
[Umbrella] RayService Refactoring

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#2548]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

The issue list is still WIP.

- [x] https://github.com/ray-project/kuberay/issues/2547
- [x] https://github.com/ray-project/kuberay/issues/2549
- [x] https://github.com/ray-project/kuberay/issues/2550
- [x] https://github.com/ray-project/kuberay/pull/2545
- [x] https://github.com/ray-project/kuberay/pull/2546
- [x] https://github.com/ray-project/kuberay/pull/2705
- [x] https://github.com/ray-project/kuberay/issues/2706
- [x] https://github.com/ray-project/kuberay/issues/2707
- [x] https://github.com/ray-project/kuberay/issues/2776
- [x] https://github.com/ray-project/kuberay/issues/2777
- [x] https://github.com/ray-project/kuberay/issues/2778
- [x] https://github.com/ray-project/kuberay/issues/2783
- [x] https://github.com/ray-project/kuberay/issues/2785
- [x] #2786 
- [x] #2751 
- [x] #2787
- [x] #2819
- [x] #2807
- [x] #2822
- [x] #2825 
- [x] #2826
- [x] #2827 
- [x] #2829 
- [x] #2828 
- [x] #2831 
- [x] #2833 
- [x] #2838 
- [x] #2842 
- [x] #2834 
- [x] #2849 
- [x] #2848 
- [x] #2854
- [x] #2853 
- [x] #2859 
- [x] #2863 
- [x] #2864 
- [x] #2866 
- [x] #2846 
- [x] #2868 
- [x] #2869
- [x] #2871 
- [x] #2872 
- [x] #2873 
- [x] #2874 
- [x] #2875 
- [x] https://github.com/ray-project/kuberay/issues/2877

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!
