### ISSUE TITLE
[Umbrella] KubeRay Authentication Support

### ISSUE THREAD

**Issue by andrewsykim** [ray-project/kuberay#2581]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

Per [KubeRay Authentication REP](https://github.com/ray-project/enhancements/blob/main/reps/2024-05-21-kuberay-authentication.md), opening an umbrella issue to capture all the work here

### Progress

- [x] https://github.com/ray-project/kuberay/pull/2578
- [x] https://github.com/ray-project/ray/pull/49080
- [ ] https://github.com/ray-project/kuberay/issues/2584
- [x] https://github.com/ray-project/kuberay/issues/2585
- [ ] https://github.com/ray-project/kuberay/issues/2586

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

**Comment by kevin85421** [comment]
In v1.3.0, the scope of KubeRay auth is to support RayCluster only. Update the tag to v1.4.0 for the rest of items.
