### ISSUE TITLE
[Umbrella] Kubectl-plugin to Beta

### ISSUE THREAD

**Issue by chiayi** [ray-project/kuberay#2608]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

As per https://github.com/ray-project/enhancements/blob/main/reps/2024-05-21-ray-kubectl-plugin.md, umbrella issue to track promotion to Beta

### Progress

- [x] #2607 
- [x] #2635 
- [x] Add doc for `create` and `delete` ray cluster command https://github.com/ray-project/ray/pull/49890
- [x] #2644 
- [x] Update doc and add examples for `kubectl ray job submit` https://github.com/ray-project/ray/pull/49890
- [x] #2429
- [x] #2486
- [x] #2614 
- [x] #2675 
- [x] #2673 
- [x] #2419
- [x] #2388

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!
