### ISSUE TITLE
[Umbrella] GCS FT API improvement

### ISSUE THREAD

**Issue by kevin85421** [ray-project/kuberay#2696]
### Search before asking

- [X] I had searched in the [issues](https://github.com/ray-project/kuberay/issues) and found no similar feature requirement.

### Description

* #2694 
* #2695
* #2697

PRs:
* #2715
* #2721
* #2726 
* #2749 
* #2731 
* #2754 
* #2755 
* #2766 
* #2772 
* #2773 
* #2760 
* #2796 
* #2855 
* #2856 

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by rueian** [comment]
👌

**Comment by kevin85421** [comment]
* Username (maybe v1.4.0 because Ray 2.41 doesn't release)
* Cleanup redis
* Validation

**Comment by rueian** [comment]
Hi @kevin85421 the two follow-ups are ready:
#2772 
#2773

**Comment by rueian** [comment]
Follow ups:
- [ ] GCS FT redis username e2e test.
- [ ] GCS FT redis username validation.

**Comment by kevin85421** [comment]
Related PRs for v1.3.0:
* #2715 
* #2721 
* #2726 
* #2749 
* #2731 
* #2754 
* #2755 
* #2766 
* #2772 
* #2773 
* #2760 
* #2796
